export enum Role {
  ROLE_ADMIN_SYSTEM = 'ROLE_ADMIN_SYSTEM',
  ROLE_ADMIN = 'ROLE_ADMIN',
  ROLE_CAISSIER = 'ROLE_CAISSIER',
  ROLE_PARTENAIRE = 'ROLE_PARTENAIRE',
  ROLE_ADMIN_PARTENAIRE = 'ROLE_ADMIN_PARTENAIRE',
  ROLE_USER_PARTENAIRE = 'ROLE_USER_PARTENAIRE'
}
